function p=userpath()
% USERPATH - Defines the paths used in this project
%    p=userpath()
%    
%    Return values:
%      p: path array
% 
% Author(s): Christian Senning
% Copyright (c) 2015 TCL, EPFL

p = [...
      'CSAtool/:',...
      'CSAtool/Error Windows:',...
      'CSAtool/gen:',...
      'CSAtool/gen/database:',...
      'CSAtool/gen/func:',...
      'CSAtool/lic:',...
      'CSAtool/messagewin:',...
      'CSAtool/models:',...
      'CSAtool/models/Energy:',...
      'CSAtool/models/cbinary_fd:',...
      'CSAtool/models/cbinary_se:',...
      'CSAtool/models/cbridge_fd:',...
      'CSAtool/models/cbridge_se:',...
      'CSAtool/models/masks:',...
      'CSAtool/models/monotonic:',...
      'CSAtool/models/monotonicbridge:',...
      'CSAtool/models/monotonicbridgemod:',...
      'CSAtool/models/splitbinary_fd:',...
      'CSAtool/models/splitbinary_se:',...
      'CSAtool/pics:',...
      'CSAtool/stat:',...
      'CSAtool/work:',...
      'CSAtool/work/ppexset:',...
      'CSAtool/work/ppexset/last:',...
      'CSAtool/work/stat:',...
    ];

